FAB-11076 Verify and Merge samples release-1.2
Create verify and merge CI jobs for fabric-samples release-1.2
branches.

Update release jobs to build only required images to publish.

Change-Id: I9146815a5f7cfaf376ee53476cca3194fbbbdf67
Signed-off-by: rameshthoomu <rameshbabu.thoomu@gmail.com>

diff --git a/jjb/releases/fabric-macros.yaml b/jjb/releases/fabric-macros.yaml
--- a/jjb/releases/fabric-macros.yaml
+++ b/jjb/releases/fabric-macros.yaml
@@ -44,11 +44,18 @@
     name: app-docker-image
     builders:
       - shell: |
-          #!/bin/bash -exu
+          #!/bin/bash -e
           set -o pipefail
 
           cd gopath/src/github.com/hyperledger/fabric
-          make docker
+          for IMAGES in peer-docker orderer-docker tools-docker ccenv; do
+              echo "---------> Build $IMAGES"
+              make $IMAGES
+            if [ $? != 0 ]; then
+              echo "----------> make $IMAGES failed"
+              exit 1
+            fi
+          done
 
 - builder:
     name: app-docker-image-release
