FABCI-108 - Modify CI jobs scripts.
1. Unnecessary IF condition is added in
fabric-chaincode-node-merge job to check the
RELEASE version, even after snapshot check.

2. Checkout to GERRIT_BRANCH where applicable
in fabric-chaincode-node-npm-release job.

3. Unnecessary IF condition is added in
fabric-sdk-node-merge job to check the
RELEASE version, even after snapshot check.

4. Add ca-fvt in fabric-ca-nightly job instead
of docker-ca-fvt in the fabricapush function.

5. Clean unwanted images and containers before
NODE tests.

6. Change make target in fabric and ca nightly jobs.

7. Don't run Integration Test on s390x platform.

Change-Id: If822a9ca2befb8ca34f3c3e3a7ddf1cb601a8d98
Signed-off-by: Sambhav Nidamarty <sambhavdutt@gmail.com>

diff --git a/jjb/fabric/fabric-jobs.yaml b/jjb/fabric/fabric-jobs.yaml
--- a/jjb/fabric/fabric-jobs.yaml
+++ b/jjb/fabric/fabric-jobs.yaml
@@ -64,11 +64,17 @@
           #!/bin/bash
 
           cd gopath/src/github.com/hyperledger/fabric || exit
-          make integration-test
-          if [ $? != 0 ]; then
-               echo "---------> make integration-test failed"
-               exit 1
+          ARCH=$(go env GOARCH)
+          if [ "$ARCH" != "s390x" ]; then
+             make integration-test
+             if [ $? != 0 ]; then
+                  echo "---------> make integration-test failed"
+                  exit 1
+             fi
+          else
+             echo "-------> Integration tests are disabled on s390x"
           fi
+
       - provide-maven-settings:
           global-settings-file: 'global-settings'
           fabric-settings-file: '{mvn-settings}'
