FABCI-140 Fix CI script errors in daily tests.
- Fix script to rectify the fail in unit-test
  coverage jobs.
- Enable fabric image push in the fabric release job.
- Fix fabric nightly build script to publish images
  from release-1.2 branch

Change-Id: I1828012c3ad32b9da9b75d3f444b1de8a1f54698
Signed-off-by: Sambhav Nidamarty <sambhavdutt@gmail.com>

diff --git a/jjb/fabric/fabric-unit-test-coverage-template.yaml b/jjb/fabric/fabric-unit-test-coverage-template.yaml
--- a/jjb/fabric/fabric-unit-test-coverage-template.yaml
+++ b/jjb/fabric/fabric-unit-test-coverage-template.yaml
@@ -43,20 +43,18 @@
           set -o pipefail
 
           cd gopath/src/github.com/hyperledger/fabric
-          if [[ "$GERRIT_BRANCH" == "master" || "$GERRIT_BRANCH" == "release-1.2" || "$GERRIT_BRANCH == "release-1.3" ]]; then
-                for target in ccenv profile; do
-                   time make $target
-                      if [ $? != 0 ]; then
-                           echo "------> make $target failed"
-                           exit 1
-                      fi
-                done
+          if [ "$GERRIT_BRANCH" == "release-1.0" ] || [ "$GERRIT_BRANCH" == "release-1.1" ]; then
+            time make profile
+               if [ $? != 0 ]; then
+                    echo "------> make profile failed"
+                    exit 1
+               fi
           else
-               time make profile
-                      if [ $? != 0 ]; then
-                           echo "------> make profile failed"
-                           exit 1
-                      fi
+            time make ccenv profile
+               if [ $? != 0 ]; then
+                    echo "------> make profile failed"
+                    exit 1
+               fi
           fi
 
     publishers:
