FAB-9419 Update unit-test coverage job config
Add ccenv make target to CI configuration as this has been
removed from the master branch with FAB-9363 change. Also,
this change set fix below issues:

- Update gopath in publish-dev-images CI job
- Add error check function
- Skip docker run command failure
- Update fabric-shim to fabric-chaincode-shim (FAB-9511)

Change-Id: Ida6b2b4ee6f143eee722cd563404900661c983f2
Signed-off-by: rameshthoomu <rameshbabu.thoomu@gmail.com>

diff --git a/jjb/fabric/fabric-unit-test-coverage-template.yaml b/jjb/fabric/fabric-unit-test-coverage-template.yaml
--- a/jjb/fabric/fabric-unit-test-coverage-template.yaml
+++ b/jjb/fabric/fabric-unit-test-coverage-template.yaml
@@ -41,7 +41,22 @@
           #!/bin/bash -eu
           set -o pipefail
 
-          cd gopath/src/github.com/hyperledger/fabric && time make profile
+          cd gopath/src/github.com/hyperledger/fabric
+          if [ $GERRIT_BRANCH = 'master' ]; then
+                for target in ccenv profile; do
+                   time make $target
+                      if [ $? != 0 ]; then
+                           echo "------> make $target failed"
+                           exit 1
+                      fi
+                done
+          else
+               time make profile
+                      if [ $? != 0 ]; then
+                           echo "------> make profile failed"
+                           exit 1
+                      fi
+          fi
 
     publishers:
       - lf-infra-publish
